name: CI Lab

on:
  push:
  pull_request:

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:

      # Étape 1 : Installation
      - name: Étape 1 - Installation
        run: echo "Installation terminée"

      # Étape 2 : Récupération du code
      - name: Étape 2 - Récupération du code
        echo "recuperation du code source"
        echo : echo"step2= ${{ vars.STEP2}}"

      # Étape 3 : Build
      - name: Étape 3 - Build
        run: echo "Build effectué"

      # Étape 4 : Tests
      - name: Étape 4 - Tests
        run: echo "Tests réussis"

      # Étape 5 : Packaging
      - name: Étape 5 - Packaging
        run: echo "Packaging terminé"

      # Étape 6 : Fin du pipeline
      - name: Étape 6 - Fin
        run: echo "Pipeline terminé avec succès"
